/**
 * THE PAGES EXTRAS: what the GitHub Pages deploy needs on top of `vite
 * build`, applied to a finished dist directory. Used twice, deliberately by
 * the same code: the pages workflow (npm run build:pages) for the real
 * deploy, and the walkthrough gate (tests/browser/pagesWalkthrough.test.ts)
 * for the tested emulation — so the artifact the lane proves and the
 * artifact the workflow ships cannot drift apart.
 *
 * Two things:
 *
 * 1. 404.html = a byte copy of index.html — THE DEEP-LINK TRICK. Pages has
 *    no SPA fallback: a reload on /retirement-planner/profile/expenses asks
 *    the host for a file that does not exist, and the only hook Pages offers
 *    is the custom 404 page. Serving the app AS the 404 page means the
 *    "error" boots the router, which reads the deep path and renders the
 *    right view. The status stays 404 (the host's choice, not ours) — fine
 *    for a human and an app, wrong only for crawlers this private tool does
 *    not court.
 *
 * 2. sw.js — the service worker, generated HERE (not authored in src)
 *    because its precache list IS the built output: every file under dist,
 *    versioned by a digest of their bytes, so the worker's identity changes
 *    exactly when the deploy's content does and never otherwise. The boring,
 *    correct update story lives in the template below:
 *      - install precaches everything and then WAITS (no skipWaiting): a
 *        new deploy never yanks the bundle out from under a live session —
 *        a simulation in flight keeps the worker files it started with;
 *      - the page (src/ui/pwa.ts) shows "Reload to update" when a new
 *        worker is waiting; the click posts SKIP_WAITING and reloads — the
 *        ONLY path to activation while a tab is open;
 *      - fetch serves precache-first for same-origin GETs, index.html for
 *        navigations (deep links work offline once installed), and NEVER
 *        touches any /api/ path — legacy HTTP mode's traffic must never be
 *        answered from a cache, stale quotes and stale records being
 *        exactly the class of bug this project exists to not have.
 *    The LANE never registers it: registration is gated on VITE_FPLAN_SW=1
 *    (set only by build:pages / pages.yml), and the walkthrough asserts
 *    zero registrations — stated plainly: the SW is tested by generation
 *    tests + the live smoke test, not by the lane.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { sha256Hex } from '../src/shared/sha256';

/** Every file under dir, as sorted relative POSIX paths. */
async function walkFiles(dir: string, prefix = ''): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const rel = prefix === '' ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) out.push(...(await walkFiles(path.join(dir, entry.name), rel)));
    else out.push(rel);
  }
  return out.sort();
}

/**
 * The sw.js source for a precache list + version. Pure — the generation
 * tests read this string. All URLs are RELATIVE: the worker resolves them
 * against its own location, so the same template is correct at any base.
 */
export function generateServiceWorkerSource(precache: string[], version: string): string {
  return `/* Generated by scripts/pagesExtras.ts — do not edit. */
/* Version is a digest of the built files: new bytes, new worker. */
const VERSION = ${JSON.stringify(version)};
const CACHE = 'fplan-precache-' + VERSION;
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  // Precache, then WAIT. No skipWaiting here: a live session keeps the
  // bundle it booted with until the user chooses to reload into the update.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  // The page's "Reload to update" button — the ONLY path to early activation.
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  // NEVER the API: legacy HTTP mode's routes must always hit the server.
  if (url.pathname.includes('/api/')) return;
  if (request.mode === 'navigate') {
    // The app shell answers every navigation (deep links included), exactly
    // as the 404 trick does when the network answers instead.
    event.respondWith(
      caches
        .match(new URL('index.html', self.location.href).href)
        .then((hit) => hit || fetch(request)),
    );
    return;
  }
  event.respondWith(caches.match(request).then((hit) => hit || fetch(request)));
});
`;
}

/** Apply every extra to a built dist directory. Returns what was written. */
export async function writePagesExtras(distDir: string): Promise<string[]> {
  const index = await fs.readFile(path.join(distDir, 'index.html'));
  await fs.writeFile(path.join(distDir, '404.html'), index);

  // The precache: everything the build produced (404.html included; sw.js
  // itself excluded — a worker must never cache its own registration). The
  // version digests every byte, so any rebuild that changes content mints a
  // new cache and an unchanged rebuild keeps the old one warm.
  const files = (await walkFiles(distDir)).filter((f) => f !== 'sw.js');
  let digestInput = '';
  for (const rel of files) {
    digestInput += `${rel}\n${sha256Hex(await fs.readFile(path.join(distDir, rel)))}\n`;
  }
  const version = sha256Hex(digestInput).slice(0, 16);
  await fs.writeFile(
    path.join(distDir, 'sw.js'),
    generateServiceWorkerSource(files, version),
  );
  return ['404.html', 'sw.js'];
}

// CLI: `tsx scripts/pagesExtras.ts <distDir>` (the build:pages script).
const invokedDirectly =
  typeof process.argv[1] === 'string' &&
  import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) {
  const distDir = process.argv[2];
  if (!distDir) {
    console.error('usage: tsx scripts/pagesExtras.ts <distDir>');
    process.exit(2);
  }
  const written = await writePagesExtras(distDir);
  console.log(`pages extras written to ${distDir}: ${written.join(', ')}`);
}
